spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;LOCK_TIMEOUT=10000
    username: sa
    hikari:
      connectionTimeout: 20000
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:sql/data.sql
  p6spy:
    logLevel: DEBUG
    log: com.p6spy.engine.spy.appender.Slf4JLogger
    appender: com.p6spy.engine.spy.appender.Slf4JLogger